config-version: 1
properties:
  chat-prefix: '&7[&dDDR&7] '
  db-type: sqlite
  permission-default: op
  check-new-version: true
  async-db-queries: true
  rate-change: 0.1
  debug-messages: false
  affect-exp: true
  affect-drops: true
  only-affect-player-kills: true
  save-frequency: 300
  minimum-rate: .2
  maximum-rate: 2
  use-metrics: true
mysql:
  hostname: localhost
  username: root
  password: CHANGEME
  port: 3306
  database: minecraft
  prefix: DDR_
mobs:
  - blaze
  - cavespider
  - skeleton
  - spider
  - zombie
  - Enderman
  - PigZombie
  - witch
excluded-worlds:
  - CreativeWorld
excluded-items: 
  - 289