properties:
  chat-prefix: '&7[&dDDR&7] '
  db-type: sqlite
  permission-default: false
  check-new-version: true
  async-db-queries: true
  rate-change: 0.1
  debug-messages: false
  affect-exp: true
  affect-drops: true
  only-affect-player-kills: true
  save-frequency: 300
mysql:
  hostname: localhost
  username: root
  password: CHANGEME
  port: 3306
  database: minecraft
  prefix: DDR_
mobs:
  - blaze
  - cavespider
  - creeper
  - ghast
  - lavaslime
  - silverfish
  - skeleton
  - slime
  - spider
  - witch
  - witherskull
  - zombie
  - Enderman
  - PigZombie