config-version: 1
properties:
  chat-prefix: '&7[&dDDR&7] '
  db-type: sqlite
  permission-default: op
  async-db-queries: true
  rate-change: 0.1
  debug-messages: false
  affect-exp: true
  affect-drops: true
  only-affect-player-kills: true
  save-frequency: 300
  minimum-rate: .2
  maximum-rate: 2
  use-metrics: true
mysql:
  hostname: localhost
  username: root
  password: CHANGEME
  port: 3306
  database: minecraft
  prefix: DDR_
mobs:
  - BLAZE
  - CAVESPIDER
  - SKELETON
  - SPIDER
  - ZOMBIE
  - ENDERMAN
  - PIGZOMBIE
  - WITCH
excluded-items: 
  - 289
world-groups: 
  default:
    - world
    - world_nether
    - world_the_end
