name: DynamicDropRate
main: com.cyprias.DynamicDropRate.Plugin
author: Cyprias
description: Dynamicly change drop rates between mobs.
version: 0.6.3

commands:
  ddr:
    description: Get available commands